### ISSUE TITLE
Unexpected disease_id format

### ISSUE THREAD

**Issue by elipapa** [opentargets/evidence_datasource_parsers#1]
@ckongEbi commented on [Thu Dec 14 2017](https://github.com/opentargets/data_release/issues/48)

In the 17.12 Phewas JSON, there are 791 evidence that has unexpected disease_id format.

e.g
"validation_errors": "u'http://purl.obolibrary.org/obo/NCBITaxon_623'
"validation_errors": "u'http://purl.obolibrary.org/obo/NCBITaxon_1392'
"validation_errors": "u'http://purl.obolibrary.org/obo/NCBITaxon_29459'

We need to re-visit the disease mapping process and fix them

---

@ckongEbi commented on [Wed Dec 20 2017](https://github.com/opentargets/data_release/issues/48#issuecomment-353045793)

@elipapa identified the possible bug and will re-visit/re-factor the phewas code to eradicate this issue.

**Comment by ckongEbi** [comment]
@elipapa can you let us know when you manage to push a fix for this so can be tested?

**Comment by elipapa** [comment]
it turns out it's not a simple fix. the ontology lookup should not result in NCBItaxon nodes. Rewriting that piece.

**Comment by elipapa** [comment]
https://github.com/opentargets/evidence_datasource_parsers/pull/7 fixes this and refactor a bunch of the codebase. 
To further improve coverage:
- [ ] map `intergenic` rsIDs to genes (~900k evidences)
- [ ] improve mappings with manual curation
