### ISSUE TITLE
UKBiobank Parser

### ISSUE THREAD

**Issue by ckongEbi** [opentargets/evidence_datasource_parsers#13]
New parser similar to GWAS needed for UKBiobank Parser. On last update, Ed has did the mappings and Gautier were to validate those and we can produce JSON for them.

**Comment by ckongEbi** [comment]
The parser is ready `https://github.com/opentargets/evidence_datasource_parsers/blob/ck-progeny/modules/UKBiobank.py`  but need to run with data with complete disease mappings

@iandunham @gkos-bio

**Comment by ckongEbi** [comment]
@ElaineMcA we will need the UKbiobank data with disease mapping curated to proceed. Check with Ed or Gautier on the curation status

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/platform #39](https://github.com/opentargets/platform/issues/39) via [**ZenHub**](https://www.zenhub.com/)
