### ISSUE TITLE
Unexpected disease_id format

### ISSUE THREAD

**Issue by elipapa** [opentargets/evidence_datasource_parsers#2]
@ckongEbi commented on [Thu Dec 14 2017](https://github.com/opentargets/data_release/issues/47)

In the `17.12` Genomics England JSON, there are 251 evidence that has unexpected disease_id format. 

e.g
"validation_errors": "u'http://purl.obolibrary.org/obo/NCBITaxon_265669'
"validation_errors": "u'http://purl.obolibrary.org/obo/NCBITaxon_36470'
"validation_errors": "u'http://purl.obolibrary.org/obo/CHEBI_31746'
"validation_errors": "u'http://purl.obolibrary.org/obo/TO_0000387'

We need to re-visit the disease mapping process and fix them

---

@ckongEbi commented on [Tue Dec 19 2017](https://github.com/opentargets/data_release/issues/47#issuecomment-352498624)

@gkos-bio upon fixing the OLS API , we manage to reduce the number of evidence that has unexpected disease_id. 

e.g of problematic API call (exact=true)
https://www.ebi.ac.uk/ols/api/search?q=VACTERL-like%20phenotype&queryFields=synonym&eact=true&ontology=efo,ordo,hpo

There is still one evidence with issue:
 "validation_errors": ("u'http://purl.obolibrary.org/obo/UBERON_0012316') 
"url": "https://panelapp.genomicsengland.co.uk/panels/57acb8268f620364dc61afd3"}]}
"panel_name": "Clefting"

Zooma is returning:
![screen shot 2017-12-18 at 17 48 16](https://user-images.githubusercontent.com/6169985/34119917-b83d2998-e41b-11e7-8620-fcdcc3695bb8.png)

---

@ckongEbi commented on [Tue Dec 19 2017](https://github.com/opentargets/data_release/issues/47#issuecomment-352788425)

Reported to SPOT team, the OLS API should return 400 error code for a bad request. When we provide a wrong parameter `eact` instead of `exact`

https://github.com/EBISPOT/OLS/issues/183#issuecomment-352787281

**Comment by ckongEbi** [comment]
this issue should be now closed
