### ISSUE TITLE
Genomics England data does not have required publication field

### ISSUE THREAD

**Issue by elipapa** [opentargets/evidence_datasource_parsers#3]
@emepyc commented on [Fri Dec 01 2017](https://github.com/opentargets/data_pipeline/issues/220)

The genomics evidence schema needs a non-empty publications array but the Genomics England PanelApp data doesn't provide one always.
In the December release, to make the schema happy, a _dummy_ publication has been added in the form: 

```
      "evidence": {
        "provenance_type": {
          "literature": {
            "references": [
              {
                "lit_id": "NA"
              }
            ]
          },

```
If the field is not mandatory it should not be required in the schema instead of bypassing the validation by including a "NA" value. Having these hacks undermine the benefits of having an schema in the first place.
As a side effect this requires including weak code in the webapp or any other consumer of the data.

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/platform #38](https://github.com/opentargets/platform/issues/38) via [**ZenHub**](https://www.zenhub.com/)
