### ISSUE TITLE
document the current SOP to map to EFO, using APIs

### ISSUE THREAD

**Issue by elipapa** [opentargets/evidence_datasource_parsers#4]

**Comment by ckongEbi** [comment]
would like to arrange a meet-up to for us next week.  

Enabling : 
1: @gkos-bio to walk us through how GE is currently doing the mapping and what are to be improved. 
2: all to be in sync of the EFO mapping strategy

**Comment by MichaelaEBI** [comment]
Gautier, who is currently invited to the Friday meeting?

Title: | Ontology mapping for Open Targets
Location: | Hinxton
When: | Fri 19 Jan 2018 10:30 – 12:00

**Comment by deniseOme** [comment]
Could someone take notes of this please? It would be useful for users.
Could be turned into a blog post. We have a backlog of ontology related posts, so this meeting could be the backbone for these posts.

If there are slides, it would be nice to have a copy as well please?

**Comment by MichaelaEBI** [comment]
I am happy to take notes. What are the topics of the ontology related posts?

**Comment by deniseOme** [comment]
I have the broad theme of "Ontology and Zooma" plus this bit from a previous blog post of ours:

"Stay tuned for more posts on the challenges we face when using ontologies or mapping diseases".
